platform :ios, '10.3'

target 'offersApp' do
    use_frameworks!

    pod 'ReactiveSwift', '~> 5.0'
    pod 'ReactiveCocoa', '~> 9.0.0'
    pod 'Result', '~> 4.1'
    pod 'Kingfisher', '~> 5.0'
    pod 'Moya/ReactiveSwift', '~> 13.0'
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'SwiftyJSON', '~> 4.0'
    pod 'NVActivityIndicatorView'
    pod 'ReachabilitySwift'
    pod 'SwipeCellKit'
    pod 'RSBarcodes_Swift'
end
